SELECT * FROM PAIS ORDER BY ID_PAIS DESC;

SELECT LOGRADOURO, CEP FROM ENDERECO WHERE UPPER( LOGRADOURO ) LIKE 'A%';

SELECT * FROM ENDERECO WHERE CEP LIKE '%0';

SELECT * FROM ENDERECO WHERE NUMERO BETWEEN 1 AND 1000;

SELECT LOGRADOURO, CEP FROM ENDERECO WHERE UPPER( LOGRADOURO ) LIKE 'RUA%' ORDER BY CEP DESC;

SELECT COUNT(*) AS "NÚMERO DE ENDEREÇOS" FROM ENDERECO;

SELECT b.ID_CIDADE, COUNT(*) AS "ENDEREÇOS" FROM ENDERECO e INNER JOIN BAIRRO b ON e.ID_BAIRRO = b.ID_BAIRRO
GROUP BY ID_ENDERECO  ;


UPDATE ENDERECO SET LOGRADOURO = 'RUA ATUALIZADA', COMPLEMENTO = 'COMPLEMENTO ATUALIZADO' WHERE ID_ENDERECO IN (2,3);

UPDATE ENDERECO SET NUMERO = 999999 WHERE ID_ENDERECO = 4;

SELECT * FROM ENDERECO ;
SELECT MAX (ID_ENDERECO) FROM ENDERECO ;
DELETE FROM ENDERECO WHERE  ID_ENDERECO ;

DELETE FROM ENDERECO e WHERE e.ID_ENDERECO ;

SELECT COUNT (*) AS ID_ENDERECO FROM ENDERECO e ;






